server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.222.165:3306/gmall_product?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useUnicode=true
  redis:
    host: 192.168.222.165
    password:
    database: 0
    port: 6379
  zipkin:
    base-url: http://192.168.222.165:9411
  rabbitmq:
    host: 192.168.222.165
    port: 5672
    username: guest
    password: guest